---
title: "Syllabus"
format: html
---

## Description

This page serves as a syllabus for the SATVI Computational Course. Details for each session can be found on their dedicated page. 

## **Module 1: Intro to R and MaRcus Training Course** 

### Session 1: Intro to R and swirl

**Topic:** Introduction to R language and environments, RStudio, and swirl self-teaching tools. 

**Instructor:** Monika Looney: monika.looney@uct.ac.za

**Date:** 15 APR 2025

**Time:** 11h00 - 12h00

**Location:** Lekgotla 4A and 4B

**Pre-learning:** Watch Session 1 pre-recorded lecture and explore the course website / GitHub. Download R, RStudio, and swirl (explained in video). Come to class with your laptop charged and ready to work through swirl in the RStudio environment.

### Session 2: MaRcus Training Course lesson 1

**Topic:** Importing data into R environment and basic visualizations with ggplot2

**Instructor:** Carly Young-Baile: carly.young-bailie@uct.ac.za

**Date:** 29 APR 2025

**Time:** 11h00 - 12h00

**Location:** Lekgotla 4A and 4B

**Pre-learning:** Watch pre-recorded lecture and review the session guide. Experiment with importing data and come to class ready to complete the assignment from [MaRcus R Training Course](https://haswal.github.io/MaRcus/01_session.html)

### Session 3: MaRcus Training Course lesson 2

**Topic:** Creating histograms and statistical summaries; combining and exporting plots 

**Instructor:** Carly Young-Baile: carly.young-bailie@uct.ac.za

**Date:** 13 MAY 2025

**Time:** 11h00 - 12h00

**Location:** Lekgotla 4A and 4B

**Pre-learning:** Watch pre-recorded lecture and review the session guide. Come to class prepared to work through the assignment from [MaRcus R Training Course](https://haswal.github.io/MaRcus/02_session.html)

### Session 4: MaRcus Training Course lesson 3

**Topic:** Basic data transformation using dplyr

**Instructor:** Carly Young-Baile: carly.young-bailie@uct.ac.za

**Date:** 27 MAY 2025

**Time:** 11h00 - 12h00

**Location:** Lekgotla 4A and 4B

**Pre-learning:** Watch pre-recorded lecture and review the session guide. Come to class prepared to complete the assignment from [MaRcus R Training Course](https://haswal.github.io/MaRcus/03_session.html)

**Note** - MaRcus Training Course lesson 4 was skipped as it covers R Markdown which will be replaced by a session on Quarto later.

### Session 5: MaRcus Training Course lesson 5

**Topic:** Continuation of data transformation using dplyr and data wrangling 

**Instructor:** Carly Young-Baile: carly.young-bailie@uct.ac.za

**Date:** 10 JUN 2025

**Time:** 11h00 - 12h00

**Location:** Lekgotla 4A and 4B

**Assignment:** Watch pre-recorded lecture and review the session guide. Come to class prepared to complete the assignment from [MaRcus R Training Course](https://haswal.github.io/MaRcus/05_session.html)

### Session 6: MaRcus Training Course lesson 6

**Topic:** Clean up data using tidyr

**Instructor:** Carly Young-Baile: carly.young-bailie@uct.ac.za

**Date:** 24 JUN 2025

**Time:** 11h00 - 12h00

**Location:** Lekgotla 4A and 4B

**Assignment:** Watch pre-recorded lecture and review the session guide. Come to class ready to complete the assignment from [MaRcus R Training Course](https://haswal.github.io/MaRcus/06_session.html)

### SELF-STUDY: MaRcus Training Course lesson 7

**Topic:** Manipulating strings with stringr and intro to regular expressions

**Instructor:** Carly Young-Baile: carly.young-bailie@uct.ac.za

**Date:** SELF-STUDY ONLY - SHORT VIDEO

**Time:** 11h00 - 12h00

**Location:** Lekgotla 4A and 4B

**Assignment:** Watch pre-recorded lecture and review the session guide. Come to class prepared to wrok through the assignment from [MaRcus R Training Course](https://haswal.github.io/MaRcus/07_session.html)

### Session 7: Data import and export

**Topic:** Importing and exporting data using R

**Instructor:** Monika Looney: monika.looney@uct.ac.za

**Date:** 08 JUL 2024

**Time:** 11h00 - 12h00

**Location:** Lekgotla 4A and 4B

**Assignment:** Watch pre-recorded lecture and review the session guide. Come to class prepared to wrok through the assignment from [MaRcus R Training


### Additional sessions to be added shortly