project:
  type: book
  output-dir: _book

book:
  title: "SATVI Computational Course"
  subtitle: "Session Guide"
  author: "SATVI Computational Group"
  date: "05 MAR 2024"
  downloads: pdf
  navbar:
    search: true
    background: light
  sidebar:
    border: true
    logo: satvi_logo.png
  chapters:
    - index.qmd
    - intro.qmd
    - installations.qmd
    - swirl.qmd
    - MarcusRTraining.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo




