---
title: "Session Recordings"
format: html
---

## Description

On this page you will find links to the Microsoft Teams recordings for each session. You will only be able to access these recordings if you already have institutional access via Teams. If you would like to access the recordings, but do not have access, please email the course instructors. 

## 2024 Session Recordings

### Session 1: Intro to R and swirl

05 MAR 2024

[Session 1 Video Recording](https://uctcloud-my.sharepoint.com/:v:/r/personal/yngcar003_myuct_ac_za/Documents/Recordings/Introductory%20Session_%20R%20Coding%20Course-20240305_104252-Meeting%20Recording.mp4?csf=1&web=1&e=un87KY&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D)

### Session 2:  MaRcus Training Course lesson 1

19 MAR 2024

[Session 2 Video Recording](https://uctcloud-my.sharepoint.com/personal/yngcar003_myuct_ac_za/_layouts/15/stream.aspx?id=%2Fpersonal%2Fyngcar003%5Fmyuct%5Fac%5Fza%2FDocuments%2FRecordings%2FSATVI%20R%20Course%2D20240319%5F110309%2DMeeting%20Recording%202%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview&ga=1)

### Session 3: MaRcus Training Course lesson 2

26 MAR 2024

[Session 3 Video Recording](https://uctcloud-my.sharepoint.com/:v:/r/personal/yngcar003_myuct_ac_za/Documents/Recordings/SATVI%20R_Computational%20Course-20240326_110027-Meeting%20Recording.mp4?csf=1&web=1&e=2emgFj&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D)


### Session 4: MaRcus Training Course lesson 3

02 APR 2024

[Session 4 Video Recording](https://uctcloud-my.sharepoint.com/:v:/g/personal/yngcar003_myuct_ac_za/EQ_o7vugBPBJnsZl-sgSLJ8BtAegS-8CMl4fgM-YhSamYg?referrer=Teams.TEAMS-ELECTRON&referrerScenario=MeetingChicletGetLink.view.view)

*Note - MaRcus Training Course lesson 4 was skipped as it covers R Markdown which will be replaced by a session on Quarto later.*

### Session 5: MaRcus Training Course lesson 5

09 APR 2024

[Session 5 Video Recording](https://uctcloud-my.sharepoint.com/:v:/g/personal/lnymon001_myuct_ac_za/EVgaOigWy4RHvEdDmGx87hMBXJiPsj9r-OgS9ex5xkIvYw?referrer=Teams.TEAMS-ELECTRON&referrerScenario=MeetingChicletGetLink.view.view)


### Session 6: MaRcus Training Course lesson 6

30 APR 2024

[Session 6 Video Recording](https://uctcloud-my.sharepoint.com/:v:/g/personal/yngcar003_myuct_ac_za/Ec-xT42msztHmyoRuBJMonEB5mveJ2K4HaAHWzsG7_nqWw?referrer=Teams.TEAMS-ELECTRON&referrerScenario=MeetingChicletGetLink.view.view)


### Session 7: MaRcus Training Course lesson 7

07 MAY 2024

[Session 7 Video Recording](https://uctcloud-my.sharepoint.com/:v:/r/personal/yngcar003_myuct_ac_za/Documents/Recordings/SATVI%20R_Computational%20Course-20240507_110312-Meeting%20Recording.mp4?csf=1&web=1&e=RGa715&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D)

### Session 8: Exporting data from R

21 MAY 2024

[Session 8 Video Recording](https://uctcloud-my.sharepoint.com/:v:/r/personal/lnymon001_myuct_ac_za/Documents/Recordings/SATVI%20R_Computational%20Course-20240521_110002-Meeting%20Recording.mp4?csf=1&web=1&e=aiPVPi&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D)