name: Add Issues to Project

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Name of the project'
        required: true
        default: 'SATVI Computational Course'
      org_name:
        description: 'Organization name (if project is an organization project)'
        required: false
        default: SATVILab

jobs:
  add-issues-to-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Add Issues to Project Action
        uses: SATVILab/actions/add-issues-to-project@v1.0.1
        with:
          project_name: ${{ github.event.inputs.project_name }}
          org_name: ${{ github.event.inputs.org_name }}
        env:
          PUSH_TO_PROJECT_TOKEN: ${{ secrets.PUSH_TO_PROJECT_TOKEN }}
